name: Build Release Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.4'
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup build environment
      run: |
        # Create a completely clean directory
        rm -rf release-package
        mkdir release-package
        
    - name: Create release package
      run: |
        # Copy ONLY the essential plugin files (exclude everything else)
        cp atr-simple-cookie-consent-banner.php release-package/
        cp atr-scb.css release-package/
        cp atr-scb.js release-package/
        
        # Verify contents - should only have 3 files
        echo "=== Files in release package ==="
        ls -la release-package/
        echo "=== Expected: 3 files only ==="
        
        # Create zip with exact name (no version numbers)
        cd release-package
        zip -r ../atr-simple-cookie-consent-banner.zip .
        
        # Verify zip contents - should only have 3 files
        echo "=== Zip file contents ==="
        unzip -l ../atr-simple-cookie-consent-banner.zip
        
        # Check file size
        echo "=== Zip file size ==="
        ls -lh ../atr-simple-cookie-consent-banner.zip
        
        # Verify no .github folder or other files
        echo "=== Verifying clean package ==="
        if unzip -l ../atr-simple-cookie-consent-banner.zip | grep -q "\.github"; then
          echo "ERROR: .github folder found in zip!"
          exit 1
        fi
        
        if unzip -l ../atr-simple-cookie-consent-banner.zip | grep -q "CHANGELOG\|README\|privacy-policy"; then
          echo "ERROR: Documentation files found in zip!"
          exit 1
        fi
        
        echo "SUCCESS: Clean package created with only essential files!"
        
    - name: Upload release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./atr-simple-cookie-consent-banner.zip
        asset_name: atr-simple-cookie-consent-banner.zip
        asset_content_type: application/zip
        
    - name: Upload workflow artifact
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: plugin-release-package
        path: atr-simple-cookie-consent-banner.zip
